### ISSUE TITLE
Issue opening saved schematics

### ISSUE THREAD

**Issue by AttackKittens** [mph-/lcapy-gui#6]
When opening saved .sch (from lgui) files in Windows 10, the schematic appears in the lower right hand corner and is partially cut off the screen. Could you open the schematic in the middle of the screen instead?

![huge_massive_problem_to_fix](https://user-images.githubusercontent.com/110282408/217955392-68a696ce-43fe-413d-919f-42304c7d3474.PNG)

**Comment by mph-** [comment]
I think that is fixed.
